### ISSUE TITLE
为什么导出的视频没有声音？

### ISSUE THREAD

**Issue by lxmymjr** [youyuge34/Mask_Danmu#1]
我是用的Mask_RCNN跑的程序。
效果不错，就是速度太慢了。。。
另外为什么导出的视频没有声音？

**Comment by youyuge34** [comment]
The speed is decided by your GPU.       
`OpenCV` doesn't have audio processing function. You can use `moviepy.editor` to combine the audio or just use some softwares like `format factory (格式工厂)` to merge the audio into video.
